-- Schema Supabase para o projeto Ta Barato Ai.
-- Rode este arquivo no SQL Editor do Supabase antes de publicar o frontend.
-- Depois configure static/js/supabase-config.js com a Project URL e a anon/publishable key.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text not null,
  email text unique,
  telefone text unique,
  endereco text,
  cep text,
  logradouro text,
  numero text,
  complemento text,
  bairro text,
  localidade text,
  uf text,
  bio text,
  foto_perfil text,
  pontos integer not null default 0,
  device_id text,
  role text not null default 'user',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.supermercados (
  id bigint generated by default as identity primary key,
  nome text not null,
  rede text,
  codigo text,
  endereco text,
  cidade text default 'Manaus',
  estado text default 'AM',
  latitude numeric,
  longitude numeric,
  logo_url text,
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.produtos (
  id bigint generated by default as identity primary key,
  nome text not null,
  categoria text,
  marca text,
  unidade text default 'un',
  codigo_barras text unique,
  imagem_url text,
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.precos (
  id bigint generated by default as identity primary key,
  produto_id bigint not null references public.produtos(id) on delete cascade,
  supermercado_id bigint not null references public.supermercados(id) on delete cascade,
  preco numeric(10,2) not null check (preco >= 0),
  preco_anterior numeric(10,2),
  atualizado_em timestamptz not null default now(),
  unique (produto_id, supermercado_id)
);

create table if not exists public.listas (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  nome text not null default 'Minha lista',
  total numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.lista_itens (
  id bigint generated by default as identity primary key,
  lista_id bigint not null references public.listas(id) on delete cascade,
  produto_id bigint references public.produtos(id) on delete set null,
  nome text not null,
  quantidade numeric(10,2) not null default 1,
  preco numeric(10,2) not null default 0,
  mercado_nome text,
  imagem_url text
);

create table if not exists public.avisos (
  id bigint generated by default as identity primary key,
  titulo text not null,
  mensagem text not null,
  tipo text default 'info',
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.validacoes_preco (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  preco_id bigint references public.precos(id) on delete cascade,
  tipo text not null,
  preco_sugerido numeric(10,2),
  foto_url text,
  status text not null default 'pendente',
  created_at timestamptz not null default now()
);

create table if not exists public.vibeconecta_posts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  autor_nome text,
  texto text not null,
  supermercado text,
  imagem_url text,
  anonimato boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.vibeconecta_comentarios (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.vibeconecta_posts(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  autor_nome text,
  texto text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.vibeconecta_likes (
  post_id bigint not null references public.vibeconecta_posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.financas_transacoes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  tipo text not null,
  categoria text,
  descricao text,
  valor numeric(12,2) not null default 0,
  data date not null default current_date,
  created_at timestamptz not null default now()
);

create table if not exists public.financas_metas (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  categoria text not null,
  valor numeric(12,2) not null default 0,
  mes text,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false)
$$;

alter table public.profiles enable row level security;
alter table public.supermercados enable row level security;
alter table public.produtos enable row level security;
alter table public.precos enable row level security;
alter table public.listas enable row level security;
alter table public.lista_itens enable row level security;
alter table public.avisos enable row level security;
alter table public.validacoes_preco enable row level security;
alter table public.vibeconecta_posts enable row level security;
alter table public.vibeconecta_comentarios enable row level security;
alter table public.vibeconecta_likes enable row level security;
alter table public.financas_transacoes enable row level security;
alter table public.financas_metas enable row level security;

create policy "profiles select own or admin" on public.profiles for select
  to authenticated using ((select auth.uid()) = id or public.is_admin());
create policy "profiles insert own" on public.profiles for insert
  to authenticated with check ((select auth.uid()) = id);
create policy "profiles update own or admin" on public.profiles for update
  to authenticated using ((select auth.uid()) = id or public.is_admin())
  with check ((select auth.uid()) = id or public.is_admin());

create policy "catalog public read" on public.produtos for select to anon, authenticated using (ativo = true or public.is_admin());
create policy "markets public read" on public.supermercados for select to anon, authenticated using (ativo = true or public.is_admin());
create policy "prices public read" on public.precos for select to anon, authenticated using (true);
create policy "catalog admin write" on public.produtos for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "markets admin write" on public.supermercados for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "prices admin write" on public.precos for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "lists owner read" on public.listas for select to authenticated using ((select auth.uid()) = user_id);
create policy "lists owner insert" on public.listas for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "lists owner delete" on public.listas for delete to authenticated using ((select auth.uid()) = user_id);
create policy "list items owner read" on public.lista_itens for select to authenticated
  using (exists (select 1 from public.listas l where l.id = lista_id and l.user_id = (select auth.uid())));
create policy "list items owner insert" on public.lista_itens for insert to authenticated
  with check (exists (select 1 from public.listas l where l.id = lista_id and l.user_id = (select auth.uid())));
create policy "list items owner delete" on public.lista_itens for delete to authenticated
  using (exists (select 1 from public.listas l where l.id = lista_id and l.user_id = (select auth.uid())));

create policy "notices public read" on public.avisos for select to anon, authenticated using (ativo = true or public.is_admin());
create policy "notices admin write" on public.avisos for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "validations own insert" on public.validacoes_preco for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "validations own/admin read" on public.validacoes_preco for select to authenticated using ((select auth.uid()) = user_id or public.is_admin());
create policy "validations admin update" on public.validacoes_preco for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "vibe posts public read" on public.vibeconecta_posts for select to anon, authenticated using (true);
create policy "vibe posts owner insert" on public.vibeconecta_posts for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "vibe posts owner delete" on public.vibeconecta_posts for delete to authenticated using ((select auth.uid()) = user_id or public.is_admin());
create policy "vibe comments public read" on public.vibeconecta_comentarios for select to anon, authenticated using (true);
create policy "vibe comments owner insert" on public.vibeconecta_comentarios for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "vibe likes public read" on public.vibeconecta_likes for select to anon, authenticated using (true);
create policy "vibe likes owner insert" on public.vibeconecta_likes for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "vibe likes owner delete" on public.vibeconecta_likes for delete to authenticated using ((select auth.uid()) = user_id);

create policy "finance owner read" on public.financas_transacoes for select to authenticated using ((select auth.uid()) = user_id);
create policy "finance owner insert" on public.financas_transacoes for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "finance owner update" on public.financas_transacoes for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "finance owner delete" on public.financas_transacoes for delete to authenticated using ((select auth.uid()) = user_id);
create policy "goals owner read" on public.financas_metas for select to authenticated using ((select auth.uid()) = user_id);
create policy "goals owner write" on public.financas_metas for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

grant usage on schema public to anon, authenticated;
grant select on public.produtos, public.supermercados, public.precos, public.avisos, public.vibeconecta_posts, public.vibeconecta_comentarios, public.vibeconecta_likes to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into public.supermercados (nome, rede, codigo, cidade, estado, logo_url)
values
  ('DB Supermercados', 'DB Supermercados', 'db', 'Manaus', 'AM', 'uploads/db_supermercado.jpg'),
  ('Nova Era', 'Nova Era', 'novaera', 'Manaus', 'AM', 'uploads/novaera_supermercado.jpg'),
  ('Assai Atacadista', 'Assai', 'assai', 'Manaus', 'AM', 'uploads/assaí.jpg')
on conflict do nothing;

insert into public.produtos (nome, categoria, marca, unidade, imagem_url)
values
  ('Arroz 5kg', 'Alimentos', 'Variada', 'pct', 'https://via.placeholder.com/300x220?text=Arroz'),
  ('Feijao 1kg', 'Alimentos', 'Variada', 'kg', 'https://via.placeholder.com/300x220?text=Feijao'),
  ('Cafe 500g', 'Alimentos', 'Variada', 'pct', 'https://via.placeholder.com/300x220?text=Cafe')
on conflict do nothing;
